import jwt, { decode } from 'jsonwebtoken'

//Middleware acts as a security checkpoint where it verifies the token which is stored in the local storage of the fronteend with the token which is generated by jwt


function auth(req,res,next){
    const token = req.headers['authorization'];
    if(!token){
        return res.status(401).json({message:"Token not found"});
    }
    jwt.verify(token,process.env.JWT_SECRET_KEY,(err,decoded)=>{
        if(err){return res.status(401).json({message:"Token did not match"})}
        req.userId = decoded.id;
        next();

    });

}
export default auth;